import type { EventAlbumPost } from '../../types/eventAlbum';

/** 공용 앨범 데모용 seed (다른 유저 SUCCESS 게시물) */
export const EVENT_ALBUM_SEED_POSTS: EventAlbumPost[] = [
  {
    id: 'album-seed-1',
    eventId: 'seed-event-gwangalli',
    zoneId: 'SUYEONG_NAMGU',
    eventTitleKo: '광안대교 야경 담기',
    eventType: 'place_auth',
    authorId: 'seed-user-minsu',
    authorNickname: '민수',
    content: '야경 미쳤다. 민락 수변에서 가로로 찍었어요.',
    likeCount: 24,
    likedByMe: false,
    comments: [
      {
        id: 'album-c-1',
        authorId: 'seed-user-yuna',
        authorNickname: '유나',
        content: '구도 너무 예뻐요!',
        createdAt: '2026-09-04T12:10:00.000Z',
      },
    ],
    visibility: 'public',
    completedAt: '2026-09-04T11:40:00.000Z',
  },
  {
    id: 'album-seed-2',
    eventId: 'seed-event-gamcheon',
    zoneId: 'WESTERN_BUSAN',
    eventTitleKo: '감천 골목 벽화 인증',
    eventType: 'object_sight',
    authorId: 'seed-user-yuna',
    authorNickname: '유나',
    content: '벽화랑 같이 찍기 성공!',
    likeCount: 11,
    likedByMe: false,
    comments: [],
    visibility: 'public',
    completedAt: '2026-09-04T09:20:00.000Z',
  },
  {
    id: 'album-seed-3',
    eventId: 'seed-event-haeundae',
    zoneId: 'HAEUNDAE_GIJANG',
    eventTitleKo: '해운대 일출 실루엣',
    eventType: 'place_auth',
    authorId: 'seed-user-jun',
    authorNickname: '준',
    likeCount: 7,
    likedByMe: false,
    comments: [],
    visibility: 'public',
    completedAt: '2026-09-03T22:05:00.000Z',
  },
  {
    id: 'album-seed-4',
    eventId: 'seed-event-jagalchi',
    zoneId: 'OLD_DOWNTOWN',
    eventTitleKo: '자갈치 골목 포토',
    eventType: 'place_auth',
    authorId: 'seed-user-hara',
    authorNickname: '하라',
    content: '비 오기 전에 겨우 찍음',
    likeCount: 3,
    likedByMe: false,
    comments: [],
    visibility: 'public',
    completedAt: '2026-09-03T16:45:00.000Z',
  },
];
