import type { AppLanguage } from '../../types/user';

/** 한국관광공사 detailIntro2 — 축제(contentTypeId=15) 필드 표시 순서 */
export const FESTIVAL_DETAIL_FIELD_ORDER = [
  'festivalgrade',
  'festivaltypetext',
  'eventstartdate',
  'eventenddate',
  'usetimefestival',
  'eventplace',
  'placeinfo',
  'agelimit',
  'discountinfofestival',
  'spendtimefestival',
  'program',
  'subevent',
  'bookingplace',
  'eventhomepage',
  'playtime',
  'sponsor1tel',
  'sponsor2tel',
] as const;

const KO_LABELS: Record<string, string> = {
  usetime: '이용 시간',
  restdate: '휴무일',
  parking: '주차',
  infocenter: '문의',
  expguide: '체험 안내',
  expagerange: '체험 연령',
  festivalgrade: '축제 등급',
  festivaltypetext: '축제 유형',
  eventstartdate: '행사 시작',
  eventenddate: '행사 종료',
  eventplace: '행사 장소',
  eventhomepage: '행사 홈페이지',
  agelimit: '관람 연령',
  bookingplace: '예매처',
  placeinfo: '행사장 안내',
  subevent: '부대 행사',
  program: '행사 프로그램',
  usetimefestival: '행사 시간',
  discountinfofestival: '할인 정보',
  spendtimefestival: '관람 소요',
  playtime: '공연 시간',
  sponsor1tel: '주최 문의',
  sponsor2tel: '주관 문의',
  spendtime: '소요 시간',
  heritage1: '세계문화유산',
  heritage2: '세계자연유산',
  heritage3: '세계기록유산',
  opendatefood: '개업일',
  restdatefood: '쉬는 날',
  packing: '포장',
  reservationfood: '예약',
  treatmenu: '대표 메뉴',
  lcnsno: '인허가 번호',
  firstmenu: '대표 메뉴',
  opentimefood: '영업 시간',
  scalefood: '규모',
  seat: '좌석',
  smoking: '흡연',
  parkingfood: '주차',
  chkbabycarriage: '유모차',
  chkcreditcard: '신용카드',
  chkpet: '반려동물',
};

const EN_LABELS: Record<string, string> = {
  usetime: 'Hours',
  restdate: 'Closed',
  parking: 'Parking',
  infocenter: 'Inquiry',
  expguide: 'Experience info',
  expagerange: 'Age range',
  festivalgrade: 'Festival grade',
  festivaltypetext: 'Festival type',
  eventstartdate: 'Starts',
  eventenddate: 'Ends',
  eventplace: 'Venue',
  eventhomepage: 'Event website',
  agelimit: 'Age limit',
  bookingplace: 'Tickets',
  placeinfo: 'Venue info',
  subevent: 'Side events',
  program: 'Program',
  usetimefestival: 'Event hours',
  discountinfofestival: 'Discounts',
  spendtimefestival: 'Duration',
  playtime: 'Show time',
  sponsor1tel: 'Organizer contact',
  sponsor2tel: 'Host contact',
  spendtime: 'Duration',
  heritage1: 'World cultural heritage',
  heritage2: 'World natural heritage',
  heritage3: 'World documentary heritage',
  opendatefood: 'Opened',
  restdatefood: 'Closed',
  packing: 'Takeout',
  reservationfood: 'Reservation',
  treatmenu: 'Signature menu',
  lcnsno: 'License no.',
  firstmenu: 'Signature menu',
  opentimefood: 'Hours',
  scalefood: 'Scale',
  seat: 'Seating',
  smoking: 'Smoking',
  parkingfood: 'Parking',
  chkbabycarriage: 'Stroller',
  chkcreditcard: 'Credit card',
  chkpet: 'Pets',
};

const JA_LABELS: Record<string, string> = {
  usetime: '利用時間',
  restdate: '休業日',
  parking: '駐車',
  infocenter: 'お問い合わせ',
  expguide: '体験案内',
  expagerange: '体験年齢',
  festivalgrade: '祭り等級',
  festivaltypetext: '祭りの種類',
  eventstartdate: '開始日',
  eventenddate: '終了日',
  eventplace: '会場',
  eventhomepage: '公式サイト',
  agelimit: '観覧年齢',
  bookingplace: '予約・チケット',
  placeinfo: '会場案内',
  subevent: '関連イベント',
  program: 'プログラム',
  usetimefestival: '開催時間',
  discountinfofestival: '割引情報',
  spendtimefestival: '所要時間',
  playtime: '公演時間',
  sponsor1tel: '主催問い合わせ',
  sponsor2tel: '主管問い合わせ',
  spendtime: '所要時間',
  heritage1: '世界文化遺産',
  heritage2: '世界自然遺産',
  heritage3: '世界記録遺産',
  opendatefood: '開業日',
  restdatefood: '休業日',
  packing: 'テイクアウト',
  reservationfood: '予約',
  treatmenu: '代表メニュー',
  lcnsno: '許可番号',
  firstmenu: '代表メニュー',
  opentimefood: '営業時間',
  scalefood: '規模',
  seat: '座席',
  smoking: '喫煙',
  parkingfood: '駐車',
  chkbabycarriage: 'ベビーカー',
  chkcreditcard: 'クレジットカード',
  chkpet: 'ペット',
};

const ZH_LABELS: Record<string, string> = {
  usetime: '使用时间',
  restdate: '休息日',
  parking: '停车',
  infocenter: '咨询',
  expguide: '体验说明',
  expagerange: '体验年龄',
  festivalgrade: '节庆等级',
  festivaltypetext: '节庆类型',
  eventstartdate: '开始日期',
  eventenddate: '结束日期',
  eventplace: '活动地点',
  eventhomepage: '活动官网',
  agelimit: '观看年龄',
  bookingplace: '购票',
  placeinfo: '场地说明',
  subevent: '配套活动',
  program: '活动节目',
  usetimefestival: '活动时间',
  discountinfofestival: '折扣信息',
  spendtimefestival: '参观时长',
  playtime: '演出时间',
  sponsor1tel: '主办咨询',
  sponsor2tel: '承办咨询',
  spendtime: '所需时间',
  heritage1: '世界文化遗产',
  heritage2: '世界自然遗产',
  heritage3: '世界记录遗产',
  opendatefood: '开业日',
  restdatefood: '休息日',
  packing: '打包',
  reservationfood: '预约',
  treatmenu: '代表菜单',
  lcnsno: '许可编号',
  firstmenu: '代表菜单',
  opentimefood: '营业时间',
  scalefood: '规模',
  seat: '座位',
  smoking: '吸烟',
  parkingfood: '停车',
  chkbabycarriage: '婴儿车',
  chkcreditcard: '信用卡',
  chkpet: '宠物',
};

export const TOURISM_DETAIL_LABELS: Record<AppLanguage, Record<string, string>> = {
  ko: KO_LABELS,
  en: EN_LABELS,
  ja: JA_LABELS,
  zh: ZH_LABELS,
};

export function tourismDetailLabel(key: string, language: AppLanguage): string {
  const normalized = key.toLowerCase();
  return TOURISM_DETAIL_LABELS[language][normalized] ?? TOURISM_DETAIL_LABELS.ko[normalized] ?? key;
}

const AVAILABILITY_VALUE: Record<AppLanguage, string> = {
  ko: '있음',
  en: 'Available',
  ja: 'あり',
  zh: '有',
};

export function tourismAvailabilityValue(language: AppLanguage): string {
  return AVAILABILITY_VALUE[language];
}

export function isTourismCheckFlagKey(key: string): boolean {
  return key.toLowerCase().startsWith('chk');
}
