import type { AppLanguage } from '../../types/user';
import { PLACE_CONTENT_TYPE } from '../../types/placesApi';

/** detailIntro2 — contentTypeId별 표시 순서 (식별자·빈 값 제외는 포맷터에서 처리) */

export const ATTRACTION_DETAIL_FIELD_ORDER = [
  'usetime',
  'useseason',
  'restdate',
  'parking',
  'infocenter',
  'opendate',
  'expguide',
  'expagerange',
  'accomcount',
  'heritage1',
  'heritage2',
  'heritage3',
  'chkbabycarriage',
  'chkcreditcard',
  'chkpet',
] as const;

export const CULTURE_DETAIL_FIELD_ORDER = [
  'usetimeculture',
  'restdateculture',
  'parkingculture',
  'parkingfee',
  'usefee',
  'infocenterculture',
  'scale',
  'spendtime',
  'discountinfo',
  'accomcountculture',
  'chkbabycarriageculture',
  'chkcreditcardculture',
  'chkpetculture',
] as const;

export const FESTIVAL_DETAIL_FIELD_ORDER = [
  'festivalgrade',
  'eventstartdate',
  'eventenddate',
  'usetimefestival',
  'playtime',
  'eventplace',
  'placeinfo',
  'agelimit',
  'discountinfofestival',
  'spendtimefestival',
  'program',
  'subevent',
  'bookingplace',
  'eventhomepage',
  'sponsor1',
  'sponsor1tel',
  'sponsor2',
  'sponsor2tel',
] as const;

export const COURSE_DETAIL_FIELD_ORDER = [
  'distance',
  'taketime',
  'schedule',
  'theme',
  'infocentertourcourse',
] as const;

export const LEISURE_DETAIL_FIELD_ORDER = [
  'usetimeleports',
  'openperiod',
  'restdateleports',
  'parkingleports',
  'parkingfeeleports',
  'usefeeleports',
  'scaleleports',
  'reservation',
  'infocenterleports',
  'expagerangeleports',
  'accomcountleports',
  'chkbabycarriageleports',
  'chkcreditcardleports',
  'chkpetleports',
] as const;

export const LODGING_DETAIL_FIELD_ORDER = [
  'checkintime',
  'checkouttime',
  'roomcount',
  'roomtype',
  'scalelodging',
  'accomcountlodging',
  'chkcooking',
  'parkinglodging',
  'foodplace',
  'subfacility',
  'reservationlodging',
  'reservationurl',
  'refundregulation',
  'pickup',
  'seminar',
  'beverage',
  'sports',
  'sauna',
  'beauty',
  'karaoke',
  'barbecue',
  'campfire',
  'bicycle',
  'fitness',
  'publicpc',
  'publicbath',
] as const;

export const SHOPPING_DETAIL_FIELD_ORDER = [
  'opentime',
  'opendateshopping',
  'restdateshopping',
  'parkingshopping',
  'saleitem',
  'saleitemcost',
  'scaleshopping',
  'shopguide',
  'fairday',
  'culturecenter',
  'restroom',
  'infocentershopping',
  'chkbabycarriageshopping',
  'chkcreditcardshopping',
  'chkpetshopping',
] as const;

export const FOOD_DETAIL_FIELD_ORDER = [
  'opentimefood',
  'restdatefood',
  'firstmenu',
  'treatmenu',
  'packing',
  'reservationfood',
  'parkingfood',
  'seat',
  'smoking',
  'scalefood',
  'kidsfacility',
  'discountinfofood',
  'opendatefood',
  'lcnsno',
  'infocenterfood',
  'chkcreditcardfood',
] as const;

export const DETAIL_FIELD_ORDER_BY_CONTENT_TYPE: Record<string, readonly string[]> = {
  [PLACE_CONTENT_TYPE.attraction]: ATTRACTION_DETAIL_FIELD_ORDER,
  [PLACE_CONTENT_TYPE.culture]: CULTURE_DETAIL_FIELD_ORDER,
  [PLACE_CONTENT_TYPE.festival]: FESTIVAL_DETAIL_FIELD_ORDER,
  [PLACE_CONTENT_TYPE.course]: COURSE_DETAIL_FIELD_ORDER,
  [PLACE_CONTENT_TYPE.leisure]: LEISURE_DETAIL_FIELD_ORDER,
  [PLACE_CONTENT_TYPE.accommodation]: LODGING_DETAIL_FIELD_ORDER,
  [PLACE_CONTENT_TYPE.shopping]: SHOPPING_DETAIL_FIELD_ORDER,
  [PLACE_CONTENT_TYPE.restaurant]: FOOD_DETAIL_FIELD_ORDER,
};

/** 숙박 부대시설 여부(1/0) 필드 */
export const LODGING_AMENITY_FLAG_KEYS = new Set([
  'seminar',
  'beverage',
  'sports',
  'sauna',
  'beauty',
  'karaoke',
  'barbecue',
  'campfire',
  'bicycle',
  'fitness',
  'publicpc',
  'publicbath',
]);

const KO_LABELS: Record<string, string> = {
  // 12 관광지
  usetime: '이용 시간',
  useseason: '이용 시기',
  restdate: '휴무일',
  parking: '주차',
  infocenter: '문의',
  opendate: '개장일',
  expguide: '체험 안내',
  expagerange: '체험 연령',
  accomcount: '수용 인원',
  heritage1: '세계문화유산',
  heritage2: '세계자연유산',
  heritage3: '세계기록유산',
  chkbabycarriage: '유모차',
  chkcreditcard: '신용카드',
  chkpet: '반려동물',
  // 14 문화시설
  usetimeculture: '이용 시간',
  restdateculture: '휴무일',
  parkingculture: '주차',
  parkingfee: '주차 요금',
  usefee: '이용 요금',
  infocenterculture: '문의',
  scale: '규모',
  spendtime: '관람 소요',
  discountinfo: '할인 정보',
  accomcountculture: '수용 인원',
  chkbabycarriageculture: '유모차',
  chkcreditcardculture: '신용카드',
  chkpetculture: '반려동물',
  // 15 축제·공연·행사
  festivalgrade: '축제 등급',
  eventstartdate: '행사 시작',
  eventenddate: '행사 종료',
  eventplace: '행사 장소',
  eventhomepage: '행사 홈페이지',
  agelimit: '관람 연령',
  bookingplace: '예매처',
  placeinfo: '행사장 안내',
  subevent: '부대 행사',
  program: '행사 프로그램',
  usetimefestival: '행사 시간',
  discountinfofestival: '할인 정보',
  spendtimefestival: '관람 소요',
  playtime: '공연 시간',
  sponsor1: '주최',
  sponsor1tel: '주최 문의',
  sponsor2: '주관',
  sponsor2tel: '주관 문의',
  // 25 여행코스
  distance: '코스 거리',
  taketime: '소요 시간',
  schedule: '일정',
  theme: '테마',
  infocentertourcourse: '문의',
  // 28 레포츠
  usetimeleports: '이용 시간',
  openperiod: '개장 기간',
  restdateleports: '휴무일',
  parkingleports: '주차',
  parkingfeeleports: '주차 요금',
  usefeeleports: '이용 요금',
  scaleleports: '규모',
  reservation: '예약 안내',
  infocenterleports: '문의',
  expagerangeleports: '체험 연령',
  accomcountleports: '수용 인원',
  chkbabycarriageleports: '유모차',
  chkcreditcardleports: '신용카드',
  chkpetleports: '반려동물',
  // 32 숙박
  checkintime: '체크인',
  checkouttime: '체크아웃',
  roomcount: '객실 수',
  roomtype: '객실 유형',
  scalelodging: '규모',
  accomcountlodging: '수용 인원',
  chkcooking: '객실 내 취사',
  parkinglodging: '주차',
  foodplace: '식음료장',
  subfacility: '부대시설',
  reservationlodging: '예약 안내',
  reservationurl: '예약 URL',
  refundregulation: '환불 규정',
  pickup: '픽업 서비스',
  seminar: '세미나실',
  beverage: '식음료 시설',
  sports: '스포츠시설',
  sauna: '사우나',
  beauty: '뷰티시설',
  karaoke: '노래방',
  barbecue: '바비큐장',
  campfire: '캠프파이어',
  bicycle: '자전거 대여',
  fitness: '휘트니스',
  publicpc: '공용 PC',
  publicbath: '공용 샤워실',
  // 38 쇼핑
  opentime: '영업 시간',
  opendateshopping: '개장일',
  restdateshopping: '휴무일',
  parkingshopping: '주차',
  saleitem: '판매 품목',
  saleitemcost: '가격대',
  scaleshopping: '규모',
  shopguide: '매장 안내',
  fairday: '장날',
  culturecenter: '문화센터',
  restroom: '화장실',
  infocentershopping: '문의',
  chkbabycarriageshopping: '유모차',
  chkcreditcardshopping: '신용카드',
  chkpetshopping: '반려동물',
  // 39 음식점
  opentimefood: '영업 시간',
  restdatefood: '쉬는 날',
  firstmenu: '대표 메뉴',
  treatmenu: '취급 메뉴',
  packing: '포장',
  reservationfood: '예약',
  parkingfood: '주차',
  seat: '좌석',
  smoking: '흡연',
  scalefood: '규모',
  kidsfacility: '유아 시설',
  discountinfofood: '할인 정보',
  opendatefood: '개업일',
  lcnsno: '인허가 번호',
  infocenterfood: '문의',
  chkcreditcardfood: '신용카드',
};

const EN_LABELS: Record<string, string> = {
  usetime: 'Hours',
  useseason: 'Season',
  restdate: 'Closed',
  parking: 'Parking',
  infocenter: 'Inquiry',
  opendate: 'Opened',
  expguide: 'Experience',
  expagerange: 'Age range',
  accomcount: 'Capacity',
  heritage1: 'World cultural heritage',
  heritage2: 'World natural heritage',
  heritage3: 'World documentary heritage',
  chkbabycarriage: 'Stroller',
  chkcreditcard: 'Credit card',
  chkpet: 'Pets',
  usetimeculture: 'Hours',
  restdateculture: 'Closed',
  parkingculture: 'Parking',
  parkingfee: 'Parking fee',
  usefee: 'Admission',
  infocenterculture: 'Inquiry',
  scale: 'Scale',
  spendtime: 'Duration',
  discountinfo: 'Discounts',
  accomcountculture: 'Capacity',
  chkbabycarriageculture: 'Stroller',
  chkcreditcardculture: 'Credit card',
  chkpetculture: 'Pets',
  festivalgrade: 'Festival grade',
  eventstartdate: 'Starts',
  eventenddate: 'Ends',
  eventplace: 'Venue',
  eventhomepage: 'Website',
  agelimit: 'Age limit',
  bookingplace: 'Tickets',
  placeinfo: 'Venue info',
  subevent: 'Side events',
  program: 'Program',
  usetimefestival: 'Event hours',
  discountinfofestival: 'Discounts',
  spendtimefestival: 'Duration',
  playtime: 'Show time',
  sponsor1: 'Organizer',
  sponsor1tel: 'Organizer contact',
  sponsor2: 'Host',
  sponsor2tel: 'Host contact',
  distance: 'Distance',
  taketime: 'Duration',
  schedule: 'Schedule',
  theme: 'Theme',
  infocentertourcourse: 'Inquiry',
  usetimeleports: 'Hours',
  openperiod: 'Open period',
  restdateleports: 'Closed',
  parkingleports: 'Parking',
  parkingfeeleports: 'Parking fee',
  usefeeleports: 'Fee',
  scaleleports: 'Scale',
  reservation: 'Reservation',
  infocenterleports: 'Inquiry',
  expagerangeleports: 'Age range',
  accomcountleports: 'Capacity',
  chkbabycarriageleports: 'Stroller',
  chkcreditcardleports: 'Credit card',
  chkpetleports: 'Pets',
  checkintime: 'Check-in',
  checkouttime: 'Check-out',
  roomcount: 'Rooms',
  roomtype: 'Room type',
  scalelodging: 'Scale',
  accomcountlodging: 'Capacity',
  chkcooking: 'In-room cooking',
  parkinglodging: 'Parking',
  foodplace: 'Dining',
  subfacility: 'Amenities',
  reservationlodging: 'Reservation',
  reservationurl: 'Booking URL',
  refundregulation: 'Refund policy',
  pickup: 'Pickup',
  seminar: 'Seminar room',
  beverage: 'Beverage',
  sports: 'Sports',
  sauna: 'Sauna',
  beauty: 'Beauty',
  karaoke: 'Karaoke',
  barbecue: 'Barbecue',
  campfire: 'Campfire',
  bicycle: 'Bike rental',
  fitness: 'Fitness',
  publicpc: 'Public PC',
  publicbath: 'Public bath',
  opentime: 'Hours',
  opendateshopping: 'Opened',
  restdateshopping: 'Closed',
  parkingshopping: 'Parking',
  saleitem: 'Items',
  saleitemcost: 'Price range',
  scaleshopping: 'Scale',
  shopguide: 'Store guide',
  fairday: 'Market day',
  culturecenter: 'Culture center',
  restroom: 'Restroom',
  infocentershopping: 'Inquiry',
  chkbabycarriageshopping: 'Stroller',
  chkcreditcardshopping: 'Credit card',
  chkpetshopping: 'Pets',
  opentimefood: 'Hours',
  restdatefood: 'Closed',
  firstmenu: 'Signature menu',
  treatmenu: 'Menu',
  packing: 'Takeout',
  reservationfood: 'Reservation',
  parkingfood: 'Parking',
  seat: 'Seating',
  smoking: 'Smoking',
  scalefood: 'Scale',
  kidsfacility: 'Kids facility',
  discountinfofood: 'Discounts',
  opendatefood: 'Opened',
  lcnsno: 'License no.',
  infocenterfood: 'Inquiry',
  chkcreditcardfood: 'Credit card',
};

const JA_LABELS: Record<string, string> = {
  usetime: '利用時間',
  useseason: '利用時期',
  restdate: '休業日',
  parking: '駐車',
  infocenter: 'お問い合わせ',
  opendate: '開業日',
  expguide: '体験案内',
  expagerange: '体験年齢',
  accomcount: '収容人数',
  heritage1: '世界文化遺産',
  heritage2: '世界自然遺産',
  heritage3: '世界記録遺産',
  chkbabycarriage: 'ベビーカー',
  chkcreditcard: 'クレジットカード',
  chkpet: 'ペット',
  usetimeculture: '利用時間',
  restdateculture: '休業日',
  parkingculture: '駐車',
  parkingfee: '駐車料金',
  usefee: '利用料金',
  infocenterculture: 'お問い合わせ',
  scale: '規模',
  spendtime: '所要時間',
  discountinfo: '割引情報',
  accomcountculture: '収容人数',
  chkbabycarriageculture: 'ベビーカー',
  chkcreditcardculture: 'クレジットカード',
  chkpetculture: 'ペット',
  festivalgrade: '祭り等級',
  eventstartdate: '開始日',
  eventenddate: '終了日',
  eventplace: '会場',
  eventhomepage: '公式サイト',
  agelimit: '観覧年齢',
  bookingplace: '予約・チケット',
  placeinfo: '会場案内',
  subevent: '関連イベント',
  program: 'プログラム',
  usetimefestival: '開催時間',
  discountinfofestival: '割引情報',
  spendtimefestival: '所要時間',
  playtime: '公演時間',
  sponsor1: '主催',
  sponsor1tel: '主催問い合わせ',
  sponsor2: '主管',
  sponsor2tel: '主管問い合わせ',
  distance: 'コース距離',
  taketime: '所要時間',
  schedule: 'スケジュール',
  theme: 'テーマ',
  infocentertourcourse: 'お問い合わせ',
  usetimeleports: '利用時間',
  openperiod: '開場期間',
  restdateleports: '休業日',
  parkingleports: '駐車',
  parkingfeeleports: '駐車料金',
  usefeeleports: '利用料金',
  scaleleports: '規模',
  reservation: '予約案内',
  infocenterleports: 'お問い合わせ',
  expagerangeleports: '体験年齢',
  accomcountleports: '収容人数',
  chkbabycarriageleports: 'ベビーカー',
  chkcreditcardleports: 'クレジットカード',
  chkpetleports: 'ペット',
  checkintime: 'チェックイン',
  checkouttime: 'チェックアウト',
  roomcount: '客室数',
  roomtype: '客室タイプ',
  scalelodging: '規模',
  accomcountlodging: '収容人数',
  chkcooking: '室内調理',
  parkinglodging: '駐車',
  foodplace: '飲食施設',
  subfacility: '付帯施設',
  reservationlodging: '予約案内',
  reservationurl: '予約URL',
  refundregulation: '返金規定',
  pickup: '送迎',
  seminar: 'セミナー室',
  beverage: '飲食施設',
  sports: 'スポーツ施設',
  sauna: 'サウナ',
  beauty: 'ビューティー',
  karaoke: 'カラオケ',
  barbecue: 'バーベキュー',
  campfire: 'キャンプファイヤー',
  bicycle: '自転車レンタル',
  fitness: 'フィットネス',
  publicpc: '共用PC',
  publicbath: '共用シャワー',
  opentime: '営業時間',
  opendateshopping: '開業日',
  restdateshopping: '休業日',
  parkingshopping: '駐車',
  saleitem: '販売品目',
  saleitemcost: '価格帯',
  scaleshopping: '規模',
  shopguide: '店舗案内',
  fairday: '市の日',
  culturecenter: '文化センター',
  restroom: 'トイレ',
  infocentershopping: 'お問い合わせ',
  chkbabycarriageshopping: 'ベビーカー',
  chkcreditcardshopping: 'クレジットカード',
  chkpetshopping: 'ペット',
  opentimefood: '営業時間',
  restdatefood: '休業日',
  firstmenu: '代表メニュー',
  treatmenu: '取扱メニュー',
  packing: 'テイクアウト',
  reservationfood: '予約',
  parkingfood: '駐車',
  seat: '座席',
  smoking: '喫煙',
  scalefood: '規模',
  kidsfacility: 'キッズ施設',
  discountinfofood: '割引情報',
  opendatefood: '開業日',
  lcnsno: '許可番号',
  infocenterfood: 'お問い合わせ',
  chkcreditcardfood: 'クレジットカード',
};

const ZH_LABELS: Record<string, string> = {
  usetime: '使用时间',
  useseason: '使用季节',
  restdate: '休息日',
  parking: '停车',
  infocenter: '咨询',
  opendate: '开业日',
  expguide: '体验说明',
  expagerange: '体验年龄',
  accomcount: '容纳人数',
  heritage1: '世界文化遗产',
  heritage2: '世界自然遗产',
  heritage3: '世界记录遗产',
  chkbabycarriage: '婴儿车',
  chkcreditcard: '信用卡',
  chkpet: '宠物',
  usetimeculture: '使用时间',
  restdateculture: '休息日',
  parkingculture: '停车',
  parkingfee: '停车费',
  usefee: '门票',
  infocenterculture: '咨询',
  scale: '规模',
  spendtime: '所需时间',
  discountinfo: '折扣信息',
  accomcountculture: '容纳人数',
  chkbabycarriageculture: '婴儿车',
  chkcreditcardculture: '信用卡',
  chkpetculture: '宠物',
  festivalgrade: '节庆等级',
  eventstartdate: '开始日期',
  eventenddate: '结束日期',
  eventplace: '活动地点',
  eventhomepage: '活动官网',
  agelimit: '观看年龄',
  bookingplace: '购票',
  placeinfo: '场地说明',
  subevent: '配套活动',
  program: '活动节目',
  usetimefestival: '活动时间',
  discountinfofestival: '折扣信息',
  spendtimefestival: '参观时长',
  playtime: '演出时间',
  sponsor1: '主办',
  sponsor1tel: '主办咨询',
  sponsor2: '承办',
  sponsor2tel: '承办咨询',
  distance: '路线距离',
  taketime: '所需时间',
  schedule: '行程',
  theme: '主题',
  infocentertourcourse: '咨询',
  usetimeleports: '使用时间',
  openperiod: '开放期间',
  restdateleports: '休息日',
  parkingleports: '停车',
  parkingfeeleports: '停车费',
  usefeeleports: '费用',
  scaleleports: '规模',
  reservation: '预约说明',
  infocenterleports: '咨询',
  expagerangeleports: '体验年龄',
  accomcountleports: '容纳人数',
  chkbabycarriageleports: '婴儿车',
  chkcreditcardleports: '信用卡',
  chkpetleports: '宠物',
  checkintime: '入住',
  checkouttime: '退房',
  roomcount: '客房数',
  roomtype: '房型',
  scalelodging: '规模',
  accomcountlodging: '容纳人数',
  chkcooking: '客房内烹饪',
  parkinglodging: '停车',
  foodplace: '餐饮',
  subfacility: '附属设施',
  reservationlodging: '预约说明',
  reservationurl: '预约链接',
  refundregulation: '退款规定',
  pickup: '接送',
  seminar: '会议室',
  beverage: '餐饮设施',
  sports: '运动设施',
  sauna: '桑拿',
  beauty: '美容设施',
  karaoke: '卡拉OK',
  barbecue: '烧烤场',
  campfire: '篝火',
  bicycle: '自行车租赁',
  fitness: '健身',
  publicpc: '公用电脑',
  publicbath: '公用淋浴',
  opentime: '营业时间',
  opendateshopping: '开业日',
  restdateshopping: '休息日',
  parkingshopping: '停车',
  saleitem: '销售品类',
  saleitemcost: '价格带',
  scaleshopping: '规模',
  shopguide: '店铺指南',
  fairday: '集市日',
  culturecenter: '文化中心',
  restroom: '卫生间',
  infocentershopping: '咨询',
  chkbabycarriageshopping: '婴儿车',
  chkcreditcardshopping: '信用卡',
  chkpetshopping: '宠物',
  opentimefood: '营业时间',
  restdatefood: '休息日',
  firstmenu: '招牌菜',
  treatmenu: '菜单',
  packing: '打包',
  reservationfood: '预约',
  parkingfood: '停车',
  seat: '座位',
  smoking: '吸烟',
  scalefood: '规模',
  kidsfacility: '儿童设施',
  discountinfofood: '折扣信息',
  opendatefood: '开业日',
  lcnsno: '许可编号',
  infocenterfood: '咨询',
  chkcreditcardfood: '信用卡',
};

export const TOURISM_DETAIL_LABELS: Record<AppLanguage, Record<string, string>> = {
  ko: KO_LABELS,
  en: EN_LABELS,
  ja: JA_LABELS,
  zh: ZH_LABELS,
};

export function tourismDetailLabel(key: string, language: AppLanguage): string {
  const normalized = key.toLowerCase();
  return TOURISM_DETAIL_LABELS[language][normalized] ?? TOURISM_DETAIL_LABELS.ko[normalized] ?? key;
}

const AVAILABILITY_VALUE: Record<AppLanguage, string> = {
  ko: '있음',
  en: 'Available',
  ja: 'あり',
  zh: '有',
};

export function tourismAvailabilityValue(language: AppLanguage): string {
  return AVAILABILITY_VALUE[language];
}

export function isTourismCheckFlagKey(key: string): boolean {
  const normalized = key.toLowerCase();
  return normalized.startsWith('chk') || LODGING_AMENITY_FLAG_KEYS.has(normalized);
}
